import React from 'react'

const Terms = ({onClick}) => {
  return (
    <article className="message is-info">
      <div className="message-header">
        Gangsta Terms of Service
        <button className="delete" onClick={e => onClick(e)}></button>
      </div>
      <div className="message-body">
        <p>Lorem stuff dolor my shizz fo shizzle, consectetizzle adipiscing dawg. Ass cool velizzle, aliquet volutpat, suscipizzle quis, gizzle black, nizzle. Pellentesque rizzle tortor. Cool eros. Fusce at dolor dapibus shut the shizzle up tempizzle away. Maurizzle nibh et turpis. Boofron izzle tortizzle. Pellentesque sizzle rhoncizzle cool. In fo shizzle habitasse platea dictumst. Hizzle dapibizzle. Fo shizzle my nizzle tellus fizzle, pretium fo shizzle, fo we gonna chung, eleifend sheezy, nunc. Cool suscipizzle. We gonna chung own yo' velizzle sizzle pizzle.</p>
        <p>Donizzle posuere auctizzle my shizz. Phasellus ma nizzle elit shiznit crackalackin pretizzle tincidunt. Break yo neck, yall a fo shizzle. Dope da bomb lacizzle shut the shizzle up away elementizzle tristique. Nunc izzle nizzle sizzle amet eros ultricizzle porta. Shizzle my nizzle crocodizzle velizzle tortor, ultricies at, hendrerit yo mamma, check out this quis, dui. Etiam velizzle fo shizzle, aliquam consequat, mah nizzle non, ma nizzle mah nizzle, turpis. Vivamizzle neque. Crizzle lorizzle. Black break it down erat ut fizzle commodo funky fresh. Fusce check it out augue eu nibh ullamcorper mattizzle. Phasellizzle its fo rizzle yo nizzle boofron. Gangster leo, sollicitudin sizzle, pizzle izzle, commodo shizzlin dizzle, dope. Donizzle yo dizzle ligula. Owned shit, go to hizzle go to hizzle ornare you son of a bizzle, owned metizzle tincidunt ante, eget mofo ma nizzle enim izzle lorem. Phasellizzle quizzle break it down, fizzle izzle, black izzle, semper izzle, sapien. Ut sizzle magna vizzle own yo'. Shiz shiznit mah nizzle, suscipizzle vitae, ghetto et, brizzle go to hizzle, velit. Crackalackin a break yo neck, yall. Sed yo mamma magna crackalackin amet shiznit iaculizzle crunk.</p>
        <p>Integizzle nizzle gizzle. Yippiyo sempizzle, gizzle eu check it out congue, dawg erizzle gizzle quam, bow wow wow elementum sapizzle leo vel nulla. Uhuh ... yih! vestibulizzle laoreet felizzle. Shit hizzle tempizzle magna. Pot interdizzle check it out check out this. Its fo rizzle urna quizzle, rhoncus gizzle, yippiyo izzle, faucibizzle at, urna. Mah nizzle eleifend things sapizzle. Maecenizzle sheezy fizzle lectizzle. Fusce cool that's the shizzle eget black ultricies crunk. Morbi mollizzle sodalizzle gangsta. Fizzle egestas, shizznit a laorizzle sollicitudizzle, shut the shizzle up velit aliquet urna, vulputate phat brizzle purizzle ut velit. Suspendisse enizzle fo shizzle own yo'. Sizzle ac boofron izzle brizzle euismod funky fresh. Phasellizzle id lorem. Nam velizzle. Suspendisse i saw beyonces tizzles and my pizzle went crizzle doggy.</p>
        <p>Prizzle egizzle hizzle. Sure away crazy dizzle izzle massa its fo rizzle pellentesque. We gonna chung tellivizzle erizzle. Owned crackalackin sapizzle, black sizzle yippiyo, vulputate vitae, condimentizzle brizzle, nunc. For sure sizzle own yo' maurizzle. Crazy fermentizzle mattizzle nunc. Morbi vulputate, away izzle ultricizzle doggy, uhuh ... yih! tellizzle cursizzle justo, sizzle fo shizzle my nizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle fo shizzle dawg enizzle. Fo shizzle fermentizzle dizzle nunc. Crackalackin dignissizzle. In hizzle habitasse away izzle. Nam sit pizzle dui. Fo shizzle sed diam. Aenizzle in risus. Nizzle bizzle, elizzle egizzle adipiscing suscipit, massa pretizzle for sure, fo shizzle mah nizzle fo rizzle, mah home g-dizzle ipsizzle crackalackin pizzle cool.</p>
        <p>Aliquam crunk, sem da bomb blandizzle posuere, fo shizzle quizzle dawg fo shizzle, sizzle mollis magna break yo neck, yall pellentesque est. Maecenizzle placerizzle, libero elementum euismizzle fermentum, ipsizzle ass gravida , izzle for sure gangster fo shizzle my nizzle sizzle shiz. Morbi black elizzle, imperdiet quizzle, go to hizzle volutpizzle, crazy et, things. Vivamizzle urna. Curabitur placerat, nulla quis cursizzle bow wow wow, felizzle da bomb facilisizzle crazy, nizzle bibendum pede crazy my shizz erizzle. Donizzle lectus. Go to hizzle fo shizzle dui check out this sizzle ornare doggy. Phat mammasay mammasa mamma oo sa, turpizzle things crazy sollicitudizzle, gangster purus sempizzle mofo, sit amizzle shut the shizzle up mi shizznit bow wow wow massa. Crizzle izzle orci. Shiz hizzle habitasse platea pimpin'. Maecenizzle tortizzle sem, funky fresh crazy, gangster vitae, shizzlin dizzle my shizz, fo. Aliquam mammasay mammasa mamma oo sa sizzle, stuff vel, ultrices quizzle, for sure nizzle, leo. Duis yippiyo magna crackalackin quizzle pulvinizzle vulputate. Lorem ipsizzle i'm in the shizzle sizzle amet, yippiyo sheezy elit.</p>
        <p>Fo shizzle for sure i'm in the shizzle. Aliquam dawg commodo da bomb. Aenizzle viverra, fo shizzle mah nizzle fo rizzle, mah home g-dizzle at vulputate crackalackin, libero urna shut the shizzle up boofron, nizzle that's the shizzle check it out fo shizzle mah nizzle fo rizzle, mah home g-dizzle izzle nunc. Donizzle shit dolizzle. Vestibulizzle boofron crunk. Da bomb elementum i'm in the shizzle its fo rizzle. Integizzle brizzle i saw beyonces tizzles and my pizzle went crizzle, shit izzle, volutpat eget, auctor eget, nizzle. Sizzle yo mamma. Sizzle nisi. Cool pot amizzle leo fo shizzle we gonna chung blandizzle ass. Quisque funky fresh tellizzle funky fresh sheezy enim. Aenizzle tempizzle dignissim gizzle.</p>
      </div>
    </article>
  )
}

export default Terms